### ISSUE TITLE
Can't reproduce the same results as neuralangelo. 

### ISSUE THREAD

**Issue by cduguet** [hugoycj/Instant-angelo#48]
Hello, 

We have succesfully captured a real scene of a saxophone with neuralangelo, and the results look decent. I am trying to reenact the same results with instant-angelo but so far I am failing. What should I do? 

This is the [dataset](https://drive.google.com/file/d/1SOV0zbAZpGikHY0QmVTBaiLqlufydvxS/view?usp=sharing), and [neuralangelo's result](https://drive.google.com/file/d/1Npj5FcP4-PW5rGCIHKkq9-pjOX1AGEFS/view?usp=sharing). 
My configs in neuralangelo were: 

```
_parent_: projects/neuralangelo/configs/base.yaml
data:
    readjust:
        center:
        - 0.0
        - 0.0
        - 0.0
        scale: 0.2
    root: /data/datasets/sax/fullres/saxophone-fullres-undistorted
    train:
        image_size:
        - 5936
        - 3956
    type: projects.neuralangelo.data
    val:
        image_size:
        - 450
        - 300
model:
    appear_embed:
        enabled: false
    object:
        sdf:
            encoding:
                coarse2fine:
                    init_active_level: 4
            mlp:
                inside_out: false

```
I am aware you have another repository to share data and results, but I am not sure how to contribute, [hence this discussion](https://github.com/hugoycj/Instant-angelo_vis/discussions/1). 

Is there anything I'm missing on instant-angelo? 

Thanks !
